<a href="https://colab.research.google.com/github/TiaErikaDev/ExerciciosPython/blob/main/11_Python_Biblioteca_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aula 13 - Mais da biblioteca Numpy

In [ ]:
import numpy as np

In [ ]:
# arange, linspace, concatenate, min, max, sum, mean, var, std

In [ ]:
np.arange(0, 10, 2)
#inicia no 0 vai até o 10 de 2 em 2, mas não inclui o 10

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(10, 50, 5)
#5 valores entre 10 e 50

array([10., 20., 30., 40., 50.])

In [ ]:
x = np.linspace(0, 100, 27)
x

array([  0.        ,   3.84615385,   7.69230769,  11.53846154,
        15.38461538,  19.23076923,  23.07692308,  26.92307692,
        30.76923077,  34.61538462,  38.46153846,  42.30769231,
        46.15384615,  50.        ,  53.84615385,  57.69230769,
        61.53846154,  65.38461538,  69.23076923,  73.07692308,
        76.92307692,  80.76923077,  84.61538462,  88.46153846,
        92.30769231,  96.15384615, 100.        ])

In [ ]:
x.shape

(27,)

In [ ]:
x.reshape(9,3)

array([[  0.        ,   3.84615385,   7.69230769],
       [ 11.53846154,  15.38461538,  19.23076923],
       [ 23.07692308,  26.92307692,  30.76923077],
       [ 34.61538462,  38.46153846,  42.30769231],
       [ 46.15384615,  50.        ,  53.84615385],
       [ 57.69230769,  61.53846154,  65.38461538],
       [ 69.23076923,  73.07692308,  76.92307692],
       [ 80.76923077,  84.61538462,  88.46153846],
       [ 92.30769231,  96.15384615, 100.        ]])

In [ ]:
x.reshape(3,3,3)

array([[[  0.        ,   3.84615385,   7.69230769],
        [ 11.53846154,  15.38461538,  19.23076923],
        [ 23.07692308,  26.92307692,  30.76923077]],

       [[ 34.61538462,  38.46153846,  42.30769231],
        [ 46.15384615,  50.        ,  53.84615385],
        [ 57.69230769,  61.53846154,  65.38461538]],

       [[ 69.23076923,  73.07692308,  76.92307692],
        [ 80.76923077,  84.61538462,  88.46153846],
        [ 92.30769231,  96.15384615, 100.        ]]])

In [ ]:
vetor1 = np.array([1,2,3])
vetor2 = np.array([1,6,9])

vetor3 = np.concatenate([vetor2, vetor1, vetor2])


In [ ]:
vetor3 = vetor3.reshape(3,3)

In [ ]:
vetor3.mean()
#média dos elementos

4.222222222222222

In [ ]:
vetor3.mean(axis = 0)
#fazer a media entre as colunas

array([1.        , 4.66666667, 7.        ])

In [ ]:
vetor3.mean(axis = 1)
#fazer a media entre as linhas

array([5.33333333, 2.        , 5.33333333])

In [ ]:
vetor3.std()
#STD = desvio padrão. 
#Raiz quadrada da variância.
#variância, medida de quanto os valores estão variando da média.

3.1544599036840864

In [ ]:
vetor3.std(axis = 1)


array([3.29983165, 0.81649658, 3.29983165])

In [ ]:
vetor3.min(axis = 1)

array([1, 1, 1])

In [ ]:
vetor3.max()

9

In [ ]:
vetor3.sum()

38

In [ ]:
vetor3.var()
#variância

9.950617283950615

In [ ]:
np.sqrt(vetor3.var())

3.1544599036840864

In [ ]:
vetor3.std()

3.1544599036840864

#Exercício Proposto